services:
  backend:
    build:
      context: ./backend/test_fullstack
      dockerfile: Dockerfile
    volumes:
    - ./backend/db-upload/profile-pictures:/app/backend/db-upload/profile-pictures
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/first_database
      - SPRING_DATASOURCE_USERNAME=sutthipongk
      - SPRING_DATASOURCE_PASSWORD=29407

  database:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=first_database
      - POSTGRES_USER=sutthipongk
      - POSTGRES_PASSWORD=29407
    ports:
      - "5432:5432"

  # file-upload:
  #   build: 
  #     context: ./backend/db-upload
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./uploads:/app/uploads
  #   depends_on:
  #     - backend
  #     - database
      
volumes:
  postgres_data: