services:
  backend:
    build:
      context: ./backend/test_fullstack
      dockerfile: Dockerfile
    volumes:
    - ./backend/db-upload/profile-pictures:/app/backend/db-upload/profile-pictures
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://10.11.60.118:33306/intern?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=P@ssw0rdR3dcr0ss

  database:
    image: mysql:8.0
    environment:
      - DB_HOST=10.11.60.118
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=intern  
      - MYSQL_USER=sa  
      - MYSQL_PASSWORD=P@ssw0rdR3dcr0ss 

    ports:
      - "33306:33306"  
    volumes:
      - mysql_data:/var/lib/mysql  

volumes:
  mysql_data:
    driver: local  